INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (1, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (2, 'To Kill a Mockingbird', 'Harper Lee', 'Fiction');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (3, '1984', 'George Orwell', 'Dystopian');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (4, 'Pride and Prejudice', 'Jane Austen', 'Romance');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (5, 'The Catcher in the Rye', 'J.D. Salinger', 'Fiction');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (6, 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (7, 'To the Lighthouse', 'Virginia Woolf', 'Modernist');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (8, 'The Alchemist', 'Paulo Coelho', 'Fiction');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (9, 'Brave New World', 'Aldous Huxley', 'Dystopian');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (10, 'Moby-Dick', 'Herman Melville', 'Adventure');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (11, 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (12, 'The Odyssey', 'Homer', 'Epic');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (13, 'Jane Eyre', 'Charlotte Bronte', 'Romance');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (14, 'The Divine Comedy', 'Dante Alighieri', 'Poetry');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (15, 'One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 'Magical Realism');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (16, 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 'Mystery');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (17, 'Anna Karenina', 'Leo Tolstoy', 'Fiction');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (18, 'Crime and Punishment', 'Fyodor Dostoevsky', 'Fiction');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (19, 'The Picture of Dorian Gray', 'Oscar Wilde', 'Gothic');
INSERT INTO TC_Book (cd_id, nb_title, nb_author, nd_genre) VALUES (20, 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy');
