DROP TABLE IF EXISTS TC_Person;
CREATE TABLE TC_Person(
    cd_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY,
    nb_name nvarchar(50) NOT NULL,
    nb_lastname nvarchar(50) NOT NULL,
    nb_email nvarchar(100) NOT NULL,
    st_active bit not null
);

CREATE TABLE TE_Account(
    cd_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 21) PRIMARY KEY,
    cd_person INTEGER NOT NULL,
    im_balance DECIMAL(14,2) NOT NULL,
    ts_created DATETIME NOT NULL,
    ts_updated DATETIME NOT NULL,
    st_active bit not null
);

ALTER TABLE TE_Account
ADD CONSTRAINT FK_TE_Account1
FOREIGN KEY (cd_person)
REFERENCES TC_Person (cd_id);

CREATE TABLE TC_MovementType(
	cd_id INTEGER PRIMARY KEY,
	nb_name nvarchar(50)
);

CREATE TABLE TH_AccountMovement(
    cd_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 21) PRIMARY KEY,
    cd_account INTEGER NOT NULL,
    cd_type INTEGER NOT NULL,
    im_amount DECIMAL(14,2) NOT NULL,
    ts_movement DATETIME NOT NULL,
);

ALTER TABLE TH_AccountMovement
ADD CONSTRAINT FK_TH_AccountMovement1
FOREIGN KEY (cd_account)
REFERENCES TE_Account (cd_id);

ALTER TABLE TH_AccountMovements
ADD CONSTRAINT FK_TH_AccountMovement2
FOREIGN KEY (cd_type)
REFERENCES TC_MovementType (cd_id);